### ISSUE TITLE
Application generate wrong code-128 barcode

### ISSUE THREAD

**Issue by GrafOrlok** [terinjokes/flipper-barcode#2]
Hello,
There is a problem with code-128.
Making a code-128 with only numbers generate a valid barcode that I can read with a device (phone, barcode scaner)
But if you try to generate a code-128 with Letters and numbers the barcode generate can't be read and differt from the real barcade.
Exemple : try to generate the barcode attach in this issue, the result on the flipper is different from the picture
![AZ982209LK](https://github.com/terinjokes/flipper-barcode/assets/145252983/b0e22321-b896-4e6b-ab1f-e7e3321493e9)

**Comment by terinjokes** [comment]
The only barcode type currently supported is EAN-13. Putting Code-128 on the Barcode Type line should have resulted in an error.

**Comment by GrafOrlok** [comment]
I don't understand, why we can choose a barcode type in the item "Create Barcode" if only EAN-13 generate a valid one ???
Why you app offering option that generate invalid barcodes ??
isn't it simpler to remove options that don't generate valid barcodes?
In any case if I can help test to improve the application do not hesitate to contact me

**Comment by GrafOrlok** [comment]
other information, I managed to generate the barcode in code-128 with the application installed via the official hub and the official firmware. However, it actually does not work if I try to generate a barcode in code-128 on the xtreme firmware

**Comment by terinjokes** [comment]
While only EAN-13 is supported currently, the intention in the future is to support more barcode types, thus you must specify what barcode type is used.

My application doesn't have an option to create a barcode, so perhaps you're using a different application.

**Comment by GrafOrlok** [comment]
so sorry I made a mistake, the app in the xtreme firmware is flipper-barcode-generator not flipper-barcode

**Comment by terinjokes** [comment]
Cool, glad you found the right place in the end. Good luck!
